### ISSUE TITLE
可以解释一下购物车demo里面的actions么

### ISSUE THREAD

**Issue by Easy-Martin** [xiaoluoboding/vue-demo-collection#1]
可以解释一下购物车demo里面的actions么
看不太明白！

**Comment by xiaoluoboding** [comment]
actions其实相当于Vue实例里的methods。这里讲的[actions](http://vuex.vuejs.org/zh-cn/actions.html)更详细点。

**Comment by Easy-Martin** [comment]
好的 文档找好久没找到！
